package api.proyecto1.interfaces.centralllamadas;

/*
 * TipoProblema se refiere al enum de tipos de problema para las llamadas
 * Los tipos de problemas se refieren al anexo B del enunciado del proyecto 1
 */
public enum TipoProblema {
 ARTICULO_NO_RECOLECTADO,
 ENTREGA_NO_REALIZADA,
 MALA_ATENCION_GESTOR,
 MALA_INFORMACION_GESTOR,
 INFORMACION_SUMINISTRADA_ERRADA,
 EXCESO_TIEMPO_CIERRE_QUEJA,
 CIERRE_QUEJA_NO_SATISFACTORIA,
 INCONFORMIDAD_SERVICIO_TRANSPORTE,
 PERDIDA_ARTICULO,
 MAL_SERVICIO_CONDUCTOR,
 INFORMACION_RUTA,
 INFORMACION_RECOLECCION,
 INFORMACION_ENTREGA,
 INFORMACION_RUTAS_HORARIOS,
 INFORMACION_PRECIOS,
 INFORMACION_PUNTOS_ATENCION
}
